### ISSUE TITLE
Dual coordinates outisde the boundaries?

### ISSUE THREAD

**Issue by tuando9627** [ryantibs/genlasso#5] opened 2019-02-09 12:20 UTC
In the example code below, when I plot the dual plot, some dual coordinates seem to be outside the boundaries, which does not make any sense. I am not sure why. If I change the set seed number then the problem may go away.

I do not know how to upload image here but the following code should produce that plot. Thanks in advance

    library(genlasso)
    set.seed(95)
    x = matrix(c(rnorm(3,2,1),rnorm(3,8,1)),ncol=1)
    no.exp = nrow(x)
    dim=ncol(x)/2
    D = matrix(0,nrow=dim*no.exp*(no.exp-1),ncol=2*dim*no.exp)
    Dindex=1
    Drow=1-2*dim
    repeat{
       j=Dindex+2*dim
       repeat{
           Drow=Drow+2*dim
           D[Drow:(Drow+2*dim-1),Dindex:(Dindex+2*dim-1)]=diag(rep(1,2*dim))
           D[Drow:(Drow+2*dim-1),j:(j+2*dim-1)]=-diag(rep(1,2*dim))
    
           if(j+2*dim-1==2*dim*no.exp){break}
           j=j+2*dim
       }
     Dindex=Dindex+2*dim
     if(Dindex==2*dim*no.exp+1-2*dim){break}
    }
    model = genlasso(x,D=D)
    plot(model,type='dual')

**Comment by ryantibs** [comment] 2019-06-20 13:35
I'm sorry this took so long to respond to.  I was just looking at this now.  A first comment is that it appears to be due to numerical instability at step 9.  I reran your example, called `model1` the model you fit, and `model2` the result of setting `svd=TRUE` in the call to `genlasso()`.  You can see that `model2` does not have the problem of dual coordinate leaving the boundary, and the two paths differ at step 9, when the first path decides to (apparently incorrectly) delete a boundary coordinate.

I'll follow up if I find a fix for the default implementation with `svd=FALSE`.

**Comment by ryantibs** [comment] 2019-06-20 15:34
I just pushed a fix to the issue in the default implementation.  The function in question was `dualpathTall()`.  You can see at line 257 of dualpathTall.R, I had written previously written comment about how c and d can be inaccurate in the "tall" D case, which is handled by this function.  (The previous comment was confusing/inaccurate, so I rephrased it in the current version.)  The issue is that c and d are themselves given by projections onto the null space of D_{-B}, see eq (30) in https://www.stat.cmu.edu/~ryantibs/papers/genlasso.pdf.  When D is tall, the null space of D_{-B} can be trivial for a good part of the path, and so these projections should just be set to zero directly, and not computed.  I added an `if()` statement to this effect in the current version, which checks the dimension of the null space from the QR decomposition that is already being computed.  It resolves your boundary set issue. 

Thanks for catching this, which led to an improvement in the code!

**Closed as completed by ryantibs** 2019-06-20 15:34 UTC
